### ISSUE TITLE
Task indexing error for sub-projects

### ISSUE THREAD

**Issue by ba1ciu** [microsoft/vscode-gradle#60] opened 2019-11-23 00:21 UTC
**Describe the bug**
Extension fails on _./gradlew --quiet tasks --all_ when refreshing task list of gradle root and sub-projects. Command works when executed manually in terminal. I prepared sample app that I attach to the issue.
[demo.zip](https://github.com/badsyntax/vscode-gradle/files/3881945/demo.zip)

**To Reproduce**
1. Open attached project in VS Code.
2. Check the output of Gradle Tasks.

**Expected behavior**
Refresh operation completes and gradle tasks are visible on the side bar.

**Environment:**

- OS: macOS 10.15.1 (19B88)
- VS Code version: 1.40.1
- Extension version: 2.1.9

**Output from "Gradle Tasks"**

```
Executing: ./gradlew --quiet tasks --all
Error providing gradle tasks: Cannot read property 'fsPath' of undefined
```

**Comment by badsyntax** [comment] 2019-11-23 06:23
Hi. Thanks for the bug report and the useful reproducible archive, this is very helpful.  The problem line is here: https://github.com/badsyntax/vscode-gradle/blob/8d0d1c3c96ef3ad90a6ef095c1e790a949a3bcae/src/tasks.ts#L217

This bad code is due to my misunderstanding of how sub-projects work in gradle. At this time the extension only supports 1 level of sub-projects instead of supporting a tree of sub-projects. 

I am actually refactoring how this all works. Currently the extension uses `gradlew --quiet tasks --all` and does some string parsing of the output using regular expressions but the plan is to use the gradle api via a custom task or plugin to list all the projects (root + sub-projects) & tasks correctly, and then build a proper tree in the explorer, without doing any dodgy regex string parsing. Once that change is done it will fix this issue. I'm doing this work in draft PR #56 but am yet to settle on a final solution. I will update this issue when I provide a fix.

**Comment by badsyntax** [comment] 2019-11-25 22:54
FYI i've got a working solution now. Refer to screenshots in #56 Fix will be released shortly.

**Comment by badsyntax** [comment] 2019-11-26 23:26
This fix is released. Make sure you're using 2.2.1

<img width="426" alt="Screenshot 2019-11-27 at 00 26 04" src="https://user-images.githubusercontent.com/102141/69680869-8fba6c00-10ac-11ea-923e-898749e5dcbf.png">

Let me know if you have any issues.

**Closed as completed** 2019-11-26 23:27 UTC
Labels: bug

**Comment by ba1ciu** [comment] 2019-11-27 09:48
Works flawlessly 🎉 Thank you

**Comment by badsyntax** [comment] 2019-11-27 13:37
Great, thanks for the feedback!
